### ISSUE TITLE
suggestions 

### ISSUE THREAD

**Issue by AroliSG** [newk5/vcmp-nodejs-plugin#1]
Server: server
 - server.deathMessage: function (bool)
 - server.joinMessage: function (bool)
 - server.taxiJump: function (bool)
 - server.vehicleOnWater: function (bool)
 - server.driveBy: function (bool)
 - 
 
 Player: player
- player.getColour: function ('RGB') -> HEX
- player.setScanline: function (bool, WHITE); <- GREEN 
- player.getScanline: function (); 
- player.Hide: function (); <- hide player from radar
- player.Show: function (); <- show player to radar
- RGB (12,12,12) | RGBA (23,23,23,23); for adding custom colours
- Vector:

**Comment by newk5** [comment]
Since v0.0.11, most of these are now possible using: server.setOption and player.setOption. You can use the global _VCMP_ object [see here](https://github.com/newk5/vcmp-nodejs-plugin/blob/master/src/main/resources/VCMPGlobals.js) to access the needed constants. For example:
```javascript
  server.setOption(VCMP.Server.Option.DriveOnWater, true);
  player.setOption(VCMP.Player.Option.WhiteScanlines, true);
  player.setOption(VCMP.Player.Option.GreenScanlines, true);
  player.setOption(VCMP.Player.Option.ShowMarkers, false);
```
To access/get the values:
```javascript
  let driveOnWaterEnabled =  server.getOption(VCMP.Server.Option.DriveOnWater);
  let hasWhiteScanlines = player.getOption(VCMP.Player.Option.WhiteScanlines);

```

**Comment by newk5** [comment]
Since v.0.1.0 it's now possible to do: getColor("RGB") which will return the following JS Object:
```javascript
{
 r: <redValue>,
 g: <greenValue>,
 b: <blueValue>,
 a: <alphaValue>
}
```
If you dont specify a parameter and just do getColour(), it will return the color as a hexadecimal integer.

.setColour now also accepts an RGB object like:
````javascript
  //this works
  player.setColour({r:54, g:215, b:150}); //rgb format
  //this works too
   player.setColour(0xFF0FF1CE); //hexadecimal format
