### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by AroliSG** [newk5/vcmp-nodejs-plugin#2]
- server.createExplosion(player.getWorld (), 2, player.getPosition().x, player.getPosition().y, player.getPosition().z, -1, true);
V8 callback signature mismatches: expected parameter size is 12, actual parameter size is 6 

- server.addPlayerClass
V8 callback signature mismatches: expected parameter size is 16, actual parameter size is 8

- when gamemode is set on server cfg, and we use  server.setGameModeText ("JS 0.0.1"); on server, gamemode does not updates
-

**Comment by newk5** [comment]
All fixed now
